project:
  type: website
  render: 
    - "*.qmd"
  output-dir: docs

website:
  title: "learning-with-quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



